// Generated by CoffeeScript 1.7.1
(function() {
  var replaceInNodes;

  if (typeof Emoji === "undefined" || Emoji === null) {
    return;
  }

  replaceInNodes = function(cont, pattern, replacement) {
    var child, _i, _len, _ref;
    switch (cont.nodeType) {
      case 3:
        cont.data = cont.data.replace(pattern, replacement);
        break;
      case 1:
        _ref = cont.childNodes;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          child = _ref[_i];
          replaceInNodes(child, pattern, replacement);
        }
    }
  };

  Emoji.editableVal = (function(func) {
    return function(cont) {
      if (arguments.callee.caller === (typeof IM !== "undefined" && IM !== null ? IM.send : void 0)) {
        replaceInNodes(cont, /\s/g, '&#8194;');
      }
      return func.apply(this, arguments);
    };
  })(Emoji.editableVal);

}).call(this);
