// Generated by CoffeeScript 1.7.1
(function() {
  var replaceEditableVal, replaceInNodes;

  replaceInNodes = function(node, pattern, replacement) {
    var child, _i, _len, _ref;
    switch (node.nodeType) {
      case 3:
        node.data = node.data.replace(pattern, replacement);
        break;
      case 1:
        _ref = node.childNodes;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          child = _ref[_i];
          replaceInNodes(child, pattern, replacement);
        }
    }
  };

  (replaceEditableVal = function() {
    if (typeof Emoji === "undefined" || Emoji === null) {
      stManager.add('emoji.js', replaceEditableVal);
      return;
    }
    return Emoji.editableVal = (function(func) {
      return function(node) {
        var caller;
        caller = arguments.callee.caller;
        if (caller === (typeof IM !== "undefined" && IM !== null ? IM.send : void 0) || caller === (typeof IM !== "undefined" && IM !== null ? IM.sendNewMsg : void 0) || caller === (typeof FastChat !== "undefined" && FastChat !== null ? FastChat.send : void 0) || caller === (typeof Composer !== "undefined" && Composer !== null ? Composer.getSendParams : void 0)) {
          replaceInNodes(node, /(^|\S\s)\s*(\s\S|$)/g, function(match) {
            return match.replace(/\s/g, '&#8194;');
          });
        }
        return func.apply(this, arguments);
      };
    })(Emoji.editableVal);
  })();

}).call(this);
